# Setup
title:               uqnq
tagline:             'uqnq.my.id'
description:         'Blog <a href="https://uqnq.uqnq.my.id" target="_blank">uqnq</a> By <a href="https://twitter.com/uqnqid" target="_blank">@uqnqid</a>.'
url:                 https://uqnq.uqnq.my.id
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              uqnq
  url:               https://twitter.com/uqnqid
  email:             uqnqdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-61724925-5
